##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.3.0-B58] date: [Mon Dec 30 15:07:32 ICT 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = selex_smc


######################################
# building variables
BOARD		=board/stm32g431cbtx_board
MCU_STARTUP	=startup_stm32g431xx.s
MCU_FAMILY	=STM32G431xx
MCU_FLASH	=STM32G431CBTx_FLASH.ld
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
$(BOARD)/Core/Src/gpio.c \
$(BOARD)/Core/Src/tim.c \
$(BOARD)/Core/Src/stm32g4xx_it.c \
$(BOARD)/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_utils.c \
$(BOARD)/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_exti.c \
$(BOARD)/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_gpio.c \
$(BOARD)/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_pwr.c \
$(BOARD)/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_tim.c \
$(BOARD)/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dma.c \
$(BOARD)/Core/Src/system_stm32g4xx.c \
$(BOARD)/Core/Src/sysmem.c \
$(BOARD)/Core/Src/syscalls.c  

C_SOURCES +=  \
$(BOARD)/Core/Extension/board.c \
$(BOARD)/Core/Extension/update_1khz_it_hardware.c \
# C app
C_SOURCES +=  \
app/main.c \
app/ISR.c \
# C components
C_SOURCES +=  \
components/sici/sici.c\
components/tle_4972_current_sensor/tle_4972_current_sensor.c \
# C services
C_SOURCES +=  \
services/maths/maths.c \
# C utils
C_SOURCES +=  \
utils/onewrite/onewrite.c \
# ASM sources
ASM_SOURCES = $(MCU_STARTUP)


# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_FULL_LL_DRIVER \
-DHSE_VALUE=8000000 \
-DHSE_STARTUP_TIMEOUT=100 \
-DLSE_STARTUP_TIMEOUT=5000 \
-DLSE_VALUE=32768 \
-DEXTERNAL_CLOCK_VALUE=12288000 \
-DHSI_VALUE=16000000 \
-DLSI_VALUE=32000 \
-DVDD_VALUE=3300 \
-DPREFETCH_ENABLE=0 \
-DINSTRUCTION_CACHE_ENABLE=1 \
-DDATA_CACHE_ENABLE=1 \
-DSTM32G431xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-I$(BOARD)/Core/Inc \
-I$(BOARD)/Drivers/STM32G4xx_HAL_Driver/Inc \
-I$(BOARD)/Drivers/CMSIS/Device/ST/STM32G4xx/Include \
-I$(BOARD)/Drivers/CMSIS/Include

#INCLUDES:=. board services components utils
C_INCLUDES	+=	\
-I$(BOARD)/Core/Extension 

# C services
C_INCLUDES	+=	\
-Iservices/maths \
# C library
C_INCLUDES	+=	\
-Iapp\
# C components
C_INCLUDES	+=	\
-Icomponents/sici \
-Icomponents/tle_4972_current_sensor \
# C utils
C_INCLUDES	+=	\
-Iutils \
-Iutils/string\
-Iutils/onewrite\
# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32G431CBTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***